[application]

# App (Project) Name
name = "screenpipe"

# Dioxus App Default Platform
# desktop, web
default_platform = "desktop"

# `build` & `serve` dist path
out_dir = "dist"

# assets file folder
asset_dir = "assets"

# [bundle]
icon = [
    # "assets/icon.icns",                                        # for macOS
    "assets/icon.ico",                                         # for Windows
    # "assets/1024.png"                                          # for Linux and as a fallback
]

[web.app]

# HTML title tag content
title = "screenpipe"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "assets"]

# include `assets` in web platform
[web.resource]

# CSS style file

style = ["tailwind.css"]

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
