[workspace]
members = ["screenpipe-server", "screenpipe-vision", "screenpipe-audio"]
exclude = []
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["louis030195 <hi@louis030195.com>"]
description = "Trigger actions based on your screen"
repository = "https://github.com/louis030195/screen-pipe"
license = "MIT OR Apache-2.0"
edition = "2021"

[workspace.dependencies]
log = "0.4"
candle = { package = "candle-core", version = "0.6.0" }
candle-nn = { package = "candle-nn", version = "0.6.0" }
candle-transformers = { package = "candle-transformers", version = "0.6.0" }
tokenizers = "0.19.1"
tracing = "0.1.37"
tokio = { version = "1.15", features = ["full", "tracing"] }

# dev
criterion = { version = "0.5.1", features = ["async_tokio"] }



