[workspace]
members = [
    "screenpipe-core",
    "screenpipe-vision",
    "screenpipe-audio",
    "screenpipe-server",

]
exclude = [
         "examples/apps/screenpipe-app-tauri/src-tauri",
    "examples/apps/screenpipe-app-dioxus",
]
resolver = "2"


[workspace.package]
version = "0.1.0"
authors = ["louis030195 <hi@louis030195.com>"]
description = ""
repository = "https://github.com/louis030195/screen-pipe"
license = "MIT OR Apache-2.0"
edition = "2021"

[workspace.dependencies]
log = "0.4"
candle = { package = "candle-core", version = "0.6.0" }
candle-nn = { package = "candle-nn", version = "0.6.0" }
candle-transformers = { package = "candle-transformers", version = "0.6.0" }
tokenizers = "0.19.1"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
tokio = { version = "1.15", features = ["full", "tracing"] }
hf-hub = "0.3.0"
crossbeam = "0.8.4"

# dev
criterion = { version = "0.5.1", features = ["async_tokio"] }




