[workspace]
members = ["screenpipe-server", "screenpipe-vision", "screenpipe-audio"]
exclude = []
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["louis030195 <hi@louis030195.com>"]
description = "Trigger actions based on your screen"
repository = "https://github.com/louis030195/screen-pipe"
license = "MIT OR Apache-2.0"
edition = "2021"

[workspace.dependencies]
log = "0.4"
candle = { package = "candle-core", version = "0.6.0", features = ["metal"] } # not sure if this cause problem if user uses CPU or CUDA? should it be a feature?
candle-nn = { package = "candle-nn", version = "0.6.0", features = ["metal"] }
candle-transformers = { package = "candle-transformers", version = "0.6.0", features = ["metal"] }
tokenizers = "0.19.1"

