[package]
name = "screenpipe-server"
version = { workspace = true }
authors = { workspace = true }
description = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

screenpipe-vision = { path = "../screenpipe-vision" }
screenpipe-audio = { path = "../screenpipe-audio" }
screenpipe-core = { path = "../screenpipe-core" }

# Image processing
image = { workspace = true }

# OCR
# rusty-tesseract = "1.1.10"
rusty-tesseract = { git = "https://github.com/louis030195/rusty-tesseract.git", branch = "main" }

# threadpool
threadpool = "1.8.1"
num_cpus = "1.0"

# Dates
chrono = { version = "0.4.31", features = ["serde"] }

# Database
sqlx = { version = "0.7", features = ["sqlite", "runtime-tokio-native-tls", "chrono", "migrate"] }

# FFmpeg bindings
ffmpeg-next = "7.0.2"

# Local Embeddings + STT
candle = { workspace = true }
candle-nn = { workspace = true }
candle-transformers = { workspace = true }
tokenizers = { workspace = true }

lazy_static = "1.4.0"
base64 = "0.21.7"
anyhow = "1.0.86"
byteorder = "1.5.0"
hf-hub = "0.3.2"
symphonia = "0.5.4"
rand = "0.8.5"
rubato = "0.15.0"

# Server
axum = "0.7.5"
tokio = { version = "1.15", features = ["full", "tracing"] }
hyper = "1.4"
tower-http = { version = "0.5.2", features = ["cors", "trace"] }
tracing-subscriber = "0.3.18"
console-subscriber = "0.3.0"

# Log
log = { workspace = true }
env_logger = "0.10"

# Cli ! shouldn't be required if using as lib
clap = { version = "4.3", features = ["derive"] }

# Memory watchdog
sysinfo = "0.29.0"

# Color 
colored = "2.0"

# Tracing
tracing = { workspace = true }

# Plugins
tower = "0.4"
futures = "0.3.17"

# Directory management
dirs = "5.0"

# Client http 
reqwest = { version = "0.12.5", features = ["json"] }

# Concurrency
crossbeam = { workspace = true }

# Friend integration
screenpipe-integrations = { path = "../screenpipe-integrations" }
async-trait = "0.1.68"

[dev-dependencies]
tempfile = "3.3.0"


# Benches
criterion = { workspace = true }
rand = "0.8"


[[bench]]
name = "db_benchmarks"
harness = false

[features]
static-ffmpeg = ["ffmpeg-next/static"]

metal = ["candle/metal", "candle-nn/metal", "candle-transformers/metal"]
cuda = ["candle/cuda", "candle-nn/cuda", "candle-transformers/cuda"]


[[bin]]
name = "screenpipe"
path = "src/bin/screenpipe-server.rs"

[[bin]]
name = "screenpipe-video"
path = "src/bin/screenpipe-video.rs"
