[package]
name = "maintain-a-log-of-my-day"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = { version = "0.30.0", features = ["chrono", "bundled", "array"] }
reqwest = { version = "0.11", features = ["json", "multipart", "blocking"] }
serde = "1.0"
serde_json = "1.0"