# # Run for macOS

# act -W .github/workflows/release-app.yml --container-architecture linux/amd64 -j release -P macos-latest=-self-hosted 

# # Run for Linux
# act -W .github/workflows/release-app.yml --container-architecture linux/amd64 -j release -P ubuntu-22.04=-self-hosted 



name: "Release app"

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-22.04, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: setup rust
        uses: dtolnay/rust-toolchain@stable

      - name: install frontend dependencies
        working-directory: examples/apps/screen-pipe-app/
        run: npm i

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: examples/apps/screen-pipe-app/
          tagName: ${{ github.ref_name }}
          releaseName: "App v__VERSION__"
          releaseBody: "See the assets to download and install this version."
          releaseDraft: true
          prerelease: false
          distPath: "../examples/apps/screen-pipe-app/dist"
          appVersion: ${{ github.ref_name }}
